# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#Cont

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'
    replaceExistingArchive: true
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/package.zip'
    destinationFolder: '$(Build.ArtifactStagingDirectory)/extracted'
    cleanDestinationFolder: true
    overwriteExistingFiles: true

- bash: |
     find "$(Build.ArtifactStagingDirectory)/extracted" -type f -name "azure-pipelines.yml" -delete

     find "$(Build.ArtifactStagingDirectory)/extracted" -type f -name "goal.png" -delete

     find "$(Build.ArtifactStagingDirectory)/extracted" -type f -name "solution.html" -delete
  displayName: 'Remove excluded files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/extracted/'
    ArtifactName: 'package'
    publishLocation: 'Container'